---
- name: Setup Nginx Web Server
  hosts: localhost
  become: true


  tasks:
  - name: Update the system
    yum:
      name: '*'
      state: latest
  - name: Install Nginx
    yum:
      name: nginx
      state: present
  - name: Create Nginx configuration file
    template:
      src: /etc/nginx/nginx.conf
      dest: /etc/nginx/nginx.conf
      mode: 0644
  - name: Start Nginx service
    service:
      name: nginx
      state: started
      enabled: true
